title:              Just a Thought Blog
email:              jeff.thomas.iii@gmail.com
description:        A blog of reflection on faith, marriage, culture, technology, and camping.
author:             Jeff Thomas III
baseurl:            "/Just-a-Thought-Blog"
url:                "https://jeffthomasiii.github.io"

# Social Profiles
twitter_username:   jeffthomasiii
github_username:    jeffthomasiii
facebook_username:  
instagram_username:  jeffthomasiii
linkedin_username:   jeffthomasiii

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
